
package ku.speed.model;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ConvertSpeeds", targetNamespace = "http://www.webserviceX.NET/", wsdlLocation = "http://www.webservicex.net/ConvertSpeed.asmx?WSDL")
public class ConvertSpeeds
    extends Service
{

    private final static URL CONVERTSPEEDS_WSDL_LOCATION;
    private final static WebServiceException CONVERTSPEEDS_EXCEPTION;
    private final static QName CONVERTSPEEDS_QNAME = new QName("http://www.webserviceX.NET/", "ConvertSpeeds");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://www.webservicex.net/ConvertSpeed.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONVERTSPEEDS_WSDL_LOCATION = url;
        CONVERTSPEEDS_EXCEPTION = e;
    }

    public ConvertSpeeds() {
        super(__getWsdlLocation(), CONVERTSPEEDS_QNAME);
    }

    public ConvertSpeeds(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONVERTSPEEDS_QNAME, features);
    }

    public ConvertSpeeds(URL wsdlLocation) {
        super(wsdlLocation, CONVERTSPEEDS_QNAME);
    }

    public ConvertSpeeds(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONVERTSPEEDS_QNAME, features);
    }

    public ConvertSpeeds(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConvertSpeeds(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConvertSpeedsSoap
     */
    @WebEndpoint(name = "ConvertSpeedsSoap")
    public ConvertSpeedsSoap getConvertSpeedsSoap() {
        return super.getPort(new QName("http://www.webserviceX.NET/", "ConvertSpeedsSoap"), ConvertSpeedsSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConvertSpeedsSoap
     */
    @WebEndpoint(name = "ConvertSpeedsSoap")
    public ConvertSpeedsSoap getConvertSpeedsSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.webserviceX.NET/", "ConvertSpeedsSoap"), ConvertSpeedsSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONVERTSPEEDS_EXCEPTION!= null) {
            throw CONVERTSPEEDS_EXCEPTION;
        }
        return CONVERTSPEEDS_WSDL_LOCATION;
    }

}
